import type { Metadata } from "next";
import "./global.css";
import React from "react";
import Header from "@/components/Header";


export const metadata: Metadata= {
    title: "CS391 MP-4",
    description: "Generated by create next app"
}

export default function RootLayout(
    {children}:
        Readonly<{children: React.ReactNode}>
) {
    return (
        <html lang="en">
            <body>
                <Header />
                {children}
            </body>
        </html>
    );
}